blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/islero/High-Performance-Backtest.Net/discussions
    about: Ask questions and discuss ideas
  - name: Documentation
    url: https://github.com/islero/High-Performance-Backtest.Net#readme
    about: Read the documentation
